import { GithubIcon } from "@mantine/ds";
import {
  IconBrandTypescript,
  IconBrandNextjs,
  IconBrandRedux,
  IconBrandReact,
  IconBrandTailwind,
  IconBrandBootstrap,
  IconBrandWordpress,
  IconBrandJavascript,
  IconBrandFigma,
  IconBrandNpm,
  IconBrandMongodb,
  IconBrandReactNative,
} from "@tabler/icons-react";

import NodeIcon from "@/assets/images/nodejs.svg";
import Express from "@/assets/images/express.png";
import NextAuth from "@/assets/images/nextauth.png";
import Pug from "@/assets/images/pug.png";

export const features = [
  {
    icon: IconBrandReact,
    title: "React.JS",
    description: "Experienced working as a Reactjs Developer",
    color: "blue",
    type: "fe",
    image: false,
  },
  {
    icon: IconBrandTypescript,
    title: "TypeScript",
    description: "Experienced working with TypeScript",
    color: "blue",
    type: "fe",
    image: false,
  },
  {
    icon: IconBrandNextjs,
    title: "NextJS",
    description:
      "Experienced using nextjs as framework of reactjs which provides faster and advanced performance in development and deployment",
    color: "dark",
    type: "fe",
    image: false,
  },
  {
    icon: IconBrandRedux,
    title: "Redux Toolkit",
    description:
      "Has also experienced using redux toolkit to build larger and complex web apps ",
    color: "violet",
    type: "fe",
    image: false,
  },
  {
    icon: IconBrandTailwind,
    title: "Tailwind",
    description: "UI Library to build large and complex web apps",
    color: "#0ea5e9",
    type: "fe",
    image: false,
  },
  {
    icon: IconBrandBootstrap,
    title: "ReactBootrap",
    description: "UI Library to build large and complex web apps",
    color: "violet",
    type: "fe",
    image: false,
  },
  {
    icon: IconBrandWordpress,
    title: "Wordpress",
    description: "",
    color: "#712cf9",
    type: "be",
    image: false,
  },
  {
    icon: IconBrandJavascript,
    title: "JavaScript",
    description: "",
    color: "yellow",
    type: "fe",
    image: false,
  },
  {
    icon: IconBrandFigma,
    title: "Figma",
    description: "",
    color: "red",
    type: "be",
    image: false,
  },
  {
    icon: GithubIcon,
    title: "Github",
    description: "",
    color: "#0d1117",
    type: "be",
    image: false,
  },
  {
    icon: IconBrandNpm,
    title: "NPM",
    description: "",
    color: "red",
    type: "be",
    image: false,
  },
  {
    icon: NodeIcon.src,
    title: "Node JS",
    description: "",
    color: "#0d1117",
    type: "be",
    image: true,
  },
  {
    icon: Express.src,
    title: "Express JS",
    description: "",
    color: "#eee",
    type: "be",
    image: true,
  },
  {
    icon: IconBrandMongodb,
    title: "Mongodb",
    description: "",
    color: "#116149",
    type: "be",
    image: false,
  },
  {
    icon: IconBrandReactNative,
    title: "React Native",
    description: "",
    color: "#282c34",
    type: "be",
    image: false,
  },
  {
    icon: NextAuth.src,
    title: "Next Auth",
    description: "",
    color: "white",
    type: "fe",
    image: true,
  },
  {
    icon: Pug.src,
    title: "Pug Templating Engine",
    description: "",
    color: "white",
    type: "be",
    image: true,
  },
];
